### ISSUE TITLE
Does not work after Upgrade UXG to firmware 3.0.7

### ISSUE THREAD

**Issue by xEn64** [unifi-utilities/uxg-boot#19]
Hi,

Installation on UXG-Pro with current Firmware 3.0.7 fails with:

 sh: 8: set: Illegal option -o pipefail

can this be fixed or know someone a workaround?

**Comment by joshuaspence** [comment]
This repo won't work anymore, see https://github.com/unifi-utilities/uxg-boot/discussions/18. I will archive the repo as we don't need a separate approach for UDM vs UXG anymore

**Comment by xEn64** [comment]
Thank you 4 quick response! And thanks for the work in general.

I have read #18 can you give me an advice, wich Component i can install to get persistent Scripts work in UXG-PRO (like the .sh files in data/on_boot)

**Comment by joshuaspence** [comment]
Any files you create will persist, at least across reboots (not sure about firmware updates). You can create a systems service to execute the scripts on boot
